### ISSUE TITLE
Please elaborate on Current functionality

### ISSUE THREAD

**Issue by lambdaupb** [duzy/wiki#1]
I just found your library and have a use for it, but it is very hard for me to judge what it currently implements.

Could you maybe elaborate on the current status a little bit?

The best place would probably be the main README.md.

I also did not see this parser implementation listed on Wikipedias list of alternative parsers: https://www.mediawiki.org/wiki/Alternative_parsers

maybe it would be good to put a link there.

Thank you very much.

**Comment by duzy** [comment]
Hi, @lambdaupb , thanks for the issue. This parser was initially used by myself. I'm just wondering it might be helpful to others. When it's getting more users, I'll be thinking about refining it. I just have to put more energy on my jobs before this.

Yes, I'd like to elaborate more details in the README when I'm free.

**Comment by duzy** [comment]
@lambdaupb I just updated the README, I hope it's helping you.

**Comment by lambdaupb** [comment]
Thanks :)
